terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
srun: error: n051: task 0: Aborted (core dumped)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
srun: error: n050: task 0: Aborted (core dumped)
